# Generated by Django 4.0 on 2022-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_technition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='custEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
