# Generated by Django 3.2.7 on 2022-10-23 06:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auditType',
            fields=[
                ('auditTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auditType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='audit',
            fields=[
                ('auditId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('auditType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.audittype')),
            ],
        ),
    ]
